version: 0.1
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./build "s3://${BUCKET_NAME}" --delete --exclude ./build/images/*
      - aws s3 sync ./build/images "s3://${BUCKET_NAME}/images" --delete --cache-control "max-age=31536000"
