version: 0.1
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync --delete --exclude images/* build/ "s3://${BUCKET_NAME}"
      - aws s3 sync --delete --cache-control "max-age=31536000" build/images "s3://${BUCKET_NAME}/images"